name: Publish to Open VSX

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm install

      - run: npm install -g @vscode/vsce ovsx

      - run: vsce package

      - run: ovsx publish *.vsix --token ${{ secrets.OPEN_VSX_TOKEN }}
